/*
  DO NOT EDIT THIS FILE MANUALLY
  - Unless you *actually* know -
  -      what you're doing.    -
*/

/*	Dictionaries Variables */

dictionaryBucket = "${dictionaryBucket}"
dictionaryBucketRegion = "${dictionaryBucketRegion}"