/*
  DO NOT EDIT THIS FILE MANUALLY
  - Unless you *actually* know -
  -      what you're doing.    -
*/

/*	Dictionaries Variables */

dictionary-us-east-1 = "arn:aws:s3:::npk-dictionary-east-1-20181029005812833000000004"
dictionary-us-east-2 = "arn:aws:s3:::npk-dictionary-east-2-20181029005812776500000003"
dictionary-us-west-1 = "arn:aws:s3:::npk-dictionary-west-1-20181029005812746900000001"
dictionary-us-west-2 = "arn:aws:s3:::npk-dictionary-west-2-20181029005812750900000002"

dictionary-us-east-1-id = "npk-dictionary-east-1-20181029005812833000000004"
dictionary-us-east-2-id = "npk-dictionary-east-2-20181029005812776500000003"
dictionary-us-west-1-id = "npk-dictionary-west-1-20181029005812746900000001"
dictionary-us-west-2-id = "npk-dictionary-west-2-20181029005812750900000002"
