/*
  DO NOT EDIT THIS FILE MANUALLY
  - Unless you *actually* know -
  -      what you're doing.    -
*/

/*	Dictionaries Variables */

dictionaryBucket = "npk-dictionary-west-2-20181029005812750900000002"